src/api/urls.py
from django.urls import path, re_path
from drf_yasg2 import openapi
from drf_yasg2.inspectors import view
from drf_yasg2.views import get_schema_view
from rest_framework.routers import SimpleRouter

from api.views import main_api_view, ArticlesViewSet

router = SimpleRouter()
router.register(r'articles', ArticlesViewSet, basename='article')
schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)

app_name = 'api'
urlpatterns = [
    path('', main_api_view, name='main'),
    *router.urls,
    # path('articles/', view.SimpleRouterDetailView.as_view(), name='articles'),
    re_path('swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

src/blog/urls.py
from django.urls import path, re_path

from blog.views import ArticlesPageListView, ArticlePageDetailView, last_articles_view, update_articles_view

app_name = 'blog'
urlpatterns = [
    path('', ArticlesPageListView.as_view(), name='articles'),
    re_path(r'^(?:article-(?P<pk>\d+)/)?$', ArticlePageDetailView.as_view(), name='article'),
    path('last-articles/', last_articles_view, name='last_articles'),
    path('update-articles/', update_articles_view, name='last_articles'),
]

src/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from main.views import TripsPageListView, TripPageDetailView, login_view, logout_view, signup_view, \
    FAQPageListView, test, AccountView, FindView, reset, ShowMessageSendMailView, ShowMessageResetPasswordView, \
    reset_password, CreateTrip, AddParticipant, ApproveParticipant

from main.views import main_page

urlpatterns = [
                  path('', main_page, name='main'),
                  path('trip/<int:pk>/', TripPageDetailView.as_view(), name='trip'),
                  path('trips/', TripsPageListView.as_view(), name='trips'),
                  path('login/', login_view, name='login'),
                  path('logout/', logout_view, name='logout'),
                  path('signup/', signup_view, name='signup'),
                  path('account/<int:pk>/', AccountView.as_view(), name='account'),
                  path('faq/', FAQPageListView.as_view(), name='faq'),
                  path('find/', FindView.as_view(), name='find'),
                  path('test/', test, name='test'),
                  path('reset/', reset, name='reset'),
                  path('sent_mail/', ShowMessageSendMailView.as_view(), name='sent_mail'),
                  path('change_password/<int:pk>', reset_password, name='change_password'),
                  path('changed_password/', ShowMessageResetPasswordView.as_view(), name='changed_password'),
                  path('create_trip/', CreateTrip.as_view(), name='create_trip'),
                  path('add_partcipant/<int:pk>/', AddParticipant.as_view(), name='add_participant'),
                  path('approve/<int:trip_id>/<int:user_id>/', ApproveParticipant.as_view(), name='approve'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/searchpeople/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('blog/', include('blog.urls')),
                  path('api/', include('api.urls')),
                  path('', include('main.urls')),
              ]

src/main/forms.py
import re

from django import forms

from main.models import User, Trip, Transport


class AuthForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'placeholder': 'Электронная почта',
        'class': 'form-floating'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Пароль',
        'class': 'form-floating'
    }))


class SignUpForm(forms.ModelForm):
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone_number', 'email')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            self.add_error('email', 'Эта почта уже зарегистрирована')
        return email

    def clean_password2(self):
        reg = re.compile(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[A-Za-z\d]{6,20}$')
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 != password2:
            self.add_error('password1', 'Пароли не совпадают')
        if not reg.match(password1):
            self.add_error('password1', 'Пароль должен содержать цифру, по одной букве латинского алфавита в верхнем и '
                                        'нижнем регистре и не менее 6 символов')
        return password1


class FindForm(forms.ModelForm):
    city = forms.CharField(max_length=50, required=False)
    date = forms.DateField(required=False)
    transport = forms.ModelMultipleChoiceField(queryset=Transport.objects.all(),
                                               required=False)

    class Meta:
        model = Trip
        fields = ('country',)


class ImageForm(forms.Form):
    avatar = forms.ImageField()


class ResetEmailForm(forms.Form):
    email = forms.EmailField()


class ResetPasswordForm(forms.Form):
    password = forms.CharField()

src/main/views.py
from datetime import datetime

from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator

from django.views.generic import ListView, DetailView, TemplateView

from api.tasks import send_email_reset_password
from main.forms import SignUpForm, AuthForm, ImageForm, FindForm, ResetPasswordForm, ResetEmailForm
from main.models import Trip, TravelParticipant, FAQ, User, Transport
from main.services import get_trips, get_available_trips, change_trip_status


@method_decorator(login_required, name='dispatch')
class ApproveParticipant(TemplateView):
    def get(self, *args, **kwargs):
        return HttpResponse(status=404)

    def post(self, *args, **kwargs):
        trip_id = self.kwargs['trip_id']
        user_id = self.kwargs['user_id']
        trip = Trip.objects.filter(id=trip_id)
        if trip is None or trip.first().author != self.request.user:
            return HttpResponse(status=404)
        travel_participant = TravelParticipant.objects.filter(trip__id=trip_id, participant__id=user_id)
        if travel_participant is None:
            return HttpResponse(status=404)
        travel_participant = travel_participant.first()
        travel_participant.is_approved = True
        travel_participant.save()
        return redirect('account', pk=self.request.user.id)


class TripsPageListView(ListView):
    model = Trip
    template_name = 'main/trips.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TripsPageListView, self).get_context_data()
        change_trip_status()
        context['trips'] = get_available_trips()
        return context


class TripPageDetailView(DetailView):
    model = Trip
    template_name = 'main/trip.html'

    def get_context_data(self, **kwargs):
        context = super(TripPageDetailView, self).get_context_data()
        trip_pk = self.kwargs['pk']
        if self.request.user.is_authenticated:
            context['exists_participant'] = TravelParticipant.objects.filter(
                trip__id=trip_pk,
                participant=self.request.user) \
                .exists()
            trip = Trip.objects.get(id=trip_pk)
            context['is_own'] = trip.author_id == self.request.user.id
        context['participants'] = TravelParticipant.objects.filter(trip__id=trip_pk, is_approved=True)
        return context


class FindView(ListView):
    model = Trip
    template_name = 'main/find.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(FindView, self).get_context_data()
        context['transports'] = Transport.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        form = FindForm(request.POST)
        trips = None
        message = ''
        if form.is_valid():
            country = form.cleaned_data['country']
            city = form.cleaned_data['city']
            transport = form.cleaned_data['transport']
            date = form.cleaned_data['date']
            trips = Trip.objects.filter(country=country, is_available=True)
            if city:
                trips = trips.filter(city=city)
            if date:
                trips = trips.filter(date=date)
            if transport:
                trips = trips.filter(transport__in=transport)
            if trips:
                message = 'Ничего не найдено. Проверьте правильность ввода.'
        else:
            for filed in form.errors:
                print(f'{filed}: {form.errors[filed].as_text()}')
        transports = Transport.objects.all()
        return render(request, self.template_name, {
            'trips': trips,
            'message': message,
            'transports': transports
        })


def main_page(request):
    trips = get_available_trips()
    response = render(request, 'main/main.html', {
        'trips': trips,
        'user': request.user,
    })
    return response


def login_view(request):
    if request.user.is_authenticated:
        return redirect('account', pk=request.user.id)
    form = None
    if request.method == 'POST':
        form = AuthForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, username=email, password=password)
            if user is None:
                form.add_error('email', 'Неправильные email или пароль')
            else:
                login(request, user)
                return redirect('account', pk=user.id)
    else:
        form = AuthForm()
    return render(request, 'main/login.html', {
        'form': form,
    })


@method_decorator(login_required, name='dispatch')
class AccountView(DetailView):
    model = User
    template_name = 'main/account.html'
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super(AccountView, self).get_context_data()
        pk = self.kwargs['pk']
        context['cur_trips'] = get_trips(pk, True)
        context['prev_trips'] = get_trips(pk, False)
        context['is_own'] = self.request.user.id == pk
        context['transports'] = Transport.objects.all()
        context['trips_participants'] = self.request.user.trips_participants.all()
        context['my_trips_participants'] = TravelParticipant.objects.filter(trip__author=self.request.user)
        return context

    def post(self, request, *args, **kwargs):
        request = self.request
        pk = self.kwargs['pk']
        if pk != request.user.id:
            return HttpResponse(status=404)
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            user = self.request.user
            user.avatar = request.FILES['avatar']
            user.save()
        else:
            for filed in form.errors:
                print(f'{filed}: {form.errors[filed].as_text()}')
        return redirect('account', pk=pk)


def logout_view(request):
    logout(request)
    return redirect('main')


def signup_view(request):
    if request.user.is_authenticated:
        return redirect('account', pk=request.user.id)
    form = None
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            password1 = form.cleaned_data['password1']
            user = form.save(commit=False)
            user.set_password(password1)
            user.save()
            login(request, user)
            return redirect('account', pk=request.user.id)
    else:
        form = SignUpForm()
    return render(request, 'main/signup.html', {
        'form': form,
    })


class FAQPageListView(ListView):
    model = FAQ
    template_name = 'main/faq.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(FAQPageListView, self).get_context_data()
        context['faqs'] = FAQ.objects.values_list().order_by('-updated_at')
        return context


def test(request):
    return render(request, 'main/test.html')


def reset(request):
    if request.user.is_authenticated:
        return redirect('account', pk=request.user.id)
    form = None
    if request.method == 'POST':
        form = ResetEmailForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            user = User.objects.get(email=email)
            if user is None:
                form.add_error('email', 'Неправильные email')
                return render(request, 'main/reset.html', {
                    'form': form
                })
            send_email_reset_password(user.id, user.email, request)
            return redirect('sent_mail')

    return render(request, 'main/reset.html', {
        'form': form
    })


class ShowMessageSendMailView(TemplateView):
    template_name = 'main/show_message.html'

    def get_context_data(self, **kwargs):
        context = super(ShowMessageSendMailView, self).get_context_data()
        context['message'] = 'Следуйте инструкции в электронной почте'
        return context


class ShowMessageResetPasswordView(TemplateView):
    template_name = 'main/show_message.html'

    def get_context_data(self, **kwargs):
        context = super(ShowMessageResetPasswordView, self).get_context_data()
        context['message'] = 'Пароль успешно изменен'
        return context


def reset_password(request, pk):
    if request.user.is_authenticated:
        return redirect('account', pk=request.user.id)
    form = None
    if request.method == 'POST':
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            user = User.objects.get(id=pk)
            user.set_password(password)
            user.save()
            return redirect('changed_password')
        else:
            for filed in form.errors:
                print(f'{filed}: {form.errors[filed].as_text()}')
    return render(request, 'main/reset_password.html')


@method_decorator(login_required, name='dispatch')
class CreateTrip(TemplateView):
    def get(self):
        return HttpResponse(status=404)

    def post(self, request):
        form = FindForm(request.POST)

        if form.is_valid():
            country = form.cleaned_data['country']
            city = form.cleaned_data['city']
            date = form.cleaned_data['date']
            trip = Trip.objects.create(
                country=country,
                city=city,
                date=date,
                author=request.user,
            )
            transports = form.cleaned_data['transport']
            if len(transports) == 0:
                transports = Transport.objects.all()
            for transport in transports:
                trip.transport.add(transport)
            if trip.date >= datetime.now().date():

src/main/templates/main/account.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Личный кабинет{% endblock %}
{% block static_files %}
{% endblock %}
{% block navbar %}
    <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
{% endblock %}
{% block content %}
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-200 position-relative">
        <div class="width-200">
            <div class="col-auto d-none d-lg-block">
                <img name="avatar" class="bd-placeholder-img" width="200" height="200" src="
                {% if user.avatar %}
                    {{ user.avatar.url }}
                {% else %}
                    {% static '/media/user.jpg' %}
                {% endif %}">
                {% if is_own %}
                    <form enctype="multipart/form-data" method="post" action="">
                        {% csrf_token %}
                        <label class="text-center mt-1" id="img_label" type="button">изменить
                            <input name="avatar" id="avatar" type="file" accept="image/*,image/png,image/jpeg"
                                   class="d-none"/>
                        </label>
                        <button type="submit" value="загрузить" id="btn-avatar" class="btn btn-light float-end"
                                disabled>
                            загрузить
                        </button>
                    </form>
                {% endif %}
            </div>
        </div>
        <div class="col p-4 d-flex flex-column position-static">
            <div class="container text-start">
                <div class="row">
                    <div class="col-sm">
                        Фамилия:
                    </div>
                    <div class="col-sm">
                        {{ user.last_name }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm">
                        Имя:
                    </div>
                    <div class="col-sm">
                        {{ user.first_name }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm">
                        Город:
                    </div>
                    <div class="col-sm">
                        {{ user.location }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if is_own %}
        <h2 class="text-start">Заявки</h2>
        <h4 class="mt-3">Исходящие</h4>
        <table class="table text-start">
            <tbody>
            {% for trip_participant in trips_participants %}
                <tr>
                    {% with trip=trip_participant.trip %}
                        <td><a href="{% url 'trip' trip.id %}">{{ trip.city }}</a></td>
                        <td>{{ trip.country }}</td>
                        <td>{{ trip.date }}</td>
                        {% if trip_participant.is_approved %}
                            <td>одобрено</td>
                        {% else %}
                            <td>на рассмотрении</td>
                        {% endif %}
                    {% endwith %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <h4 class="mt-3">Входящие</h4>
        <table class="table text-start">
            <tbody>
            {% for my_trip_participant in my_trips_participants %}
                <tr>
                    {% with user=my_trip_participant.participant %}
                        {% if not user is None %}
                            <td><a href="{% url 'account' user.id %}">{{ user.first_name }} {{ user.last_name }}</a>
                            </td>
                            <td>{{ user.phone_number }}</td>
                            {% with trip=my_trip_participant.trip %}
                                <td><a href="{% url 'trip' trip.id %}">{{ trip.city }}</a></td>
                                {% if my_trip_participant.is_approved %}
                                    <td>одобрено</td>
                                {% else %}
                                    <td>
                                        <form action="{% url 'approve' trip.id user.id %}" method="post">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-default">одобрить</button>
                                        </form>
                                    </td>
                                {% endif %}
                            {% endwith %}
                        {% endif %}
                    {% endwith %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
    <h2 class="text-start">Поездки</h2>
    <h4 class="mt-3">Текущие:</h4>
    <table class="table text-start">
        <tbody>
        {% for cur_trip in cur_trips %}
            <tr>
                <td><a href="{% url 'trip' cur_trip.id %}">{{ cur_trip.city }}</a></td>
                <td>{{ cur_trip.country }}</td>
                <td>{{ cur_trip.date }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <h4> Архивные:</h4>
    <table class="table text-start">
        <tbody>
        {% for prev_trip in prev_trips %}
            <tr>
                <td><a href="{% url 'trip' prev_trip.id %}">{{ prev_trip.city }}</a></td>
                <td>{{ prev_trip.country }}</td>
                <td>{{ prev_trip.date }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_own %}
        <h4>Создать поездку</h4>
        <form action="{% url 'create_trip' %}" method="post" class="form-group mb-5">
            {% csrf_token %}
            <label>
                <input type="text" class="form-control" name="country" placeholder="Страна" required>
            </label>
            <label>
                <input type="text" class="form-control" name="city" placeholder="Город" required>
            </label>
            <label class="dropdown form-control">
                <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1"
                        data-bs-toggle="dropdown" aria-expanded="false">
                    Транспорт
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1" aria-required="true">
                    {% for transport in transports %}
                        <li><label class="form-check-label"><input type="checkbox" class="form-check-input"
                                                                   name="transport"
                                                                   value="{{ transport.id }}"> {{ transport }}
                        </label></li>
                    {% endfor %}
                </ul>
            </label>
            <input type="date" class="form-control" name="date" required>
            <button type="submit" class="btn form-control btn-light">Создать</button>
        </form>
    {% endif %}
    <div class="mb-5"><h4><a href="{% url 'api:article-list' %}">Создать статью</a></h4></div>
{% endblock %}
{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script rel="stylesheet" src="{% static 'js/account.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
            crossorigin="anonymous"></script>
{% endblock %}

src/main/templates/main/base.html
{% extends 'main/main_base.html' %}

{% block base_content %}
    <main class="px-3 cover-container">
        {% block content %}{% endblock %}
    </main>
{% endblock %}

src/main/templates/main/faq.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="text-start">
        <h2>Часто задаваемые вопросы</h2>
        <div class="mt-5">
            {% for id, created_at, updated_at, question, answer in faqs %}
                <li>
                    <h5>{{ question }}</h5>
                    <p>{{ answer }}</p>
                </li>
            {% endfor %}
        </div>
    </div>
{% endblock %}

src/main/templates/main/find.html
{% extends 'main/base.html' %}
{% block title %}Поиск{% endblock %}
{% block static_files %}
{% endblock %}
{% block content %}
    <div class="container mt-5">
        <form action="" method="post" class="form-group mb-5">
            {% csrf_token %}
            <label>
                <input type="text" class="form-control" name="country" placeholder="Страна" required>
            </label>
            <label>
                <input type="text" class="form-control" name="city" placeholder="Город">
            </label>
            <label class="dropdown form-control">
                <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1"
                        data-bs-toggle="dropdown" aria-expanded="false">
                    Транспорт
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1" aria-required="true">
                    {% for transport in transports %}
                        <li><label class="form-check-label"><input type="checkbox" class="form-check-input"
                                                                   name="transport"
                                                                   value="{{ transport.id }}"> {{ transport }}
                        </label></li>
                    {% endfor %}
                </ul>
            </label>
                <input type="date" class="form-control" name="date">
                <button type="submit" class="btn form-control btn-light">Найти</button>
        </form>
        {% if trips %}
            {% include 'main/partials/trip.html' with trips=trips %}
        {% else %}
            {{ message }}
        {% endif %}
    </div>
{% endblock %}
{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
            crossorigin="anonymous"></script>
{% endblock %}

src/main/templates/main/login.html
{% extends "main/base.html" %}
{% load static %}
{% block title_name %}Вход{% endblock %}
{% block static_files %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block content %}
    <div class="form-signin">
        <form action="" method="post">
            {% csrf_token %}
            {% if form.errors %}
                {% for field, error in form.errors.items %}
                    <b>{{ error }}</b>
                {% endfor %}
            {% endif %}
            <h1 class="h3 mb-3 fw-normal">Вход</h1>

            <div class="form-floating">
                <input type="email" name="email" class="form-control first" id="floatingInput" placeholder="name@example.com">
                <label for="floatingInput" class="text-dark">Email</label>
            </div>
            <div class="form-floating">
                <input type="password" name="password" class="form-control last" id="floatingPassword" placeholder="Password">
                <label for="floatingPassword" class="text-dark">Пароль</label>
            </div>
            <button class="w-100 btn btn-lg btn-primary mt-3" type="submit">Войти</button>
        </form>

    </div>
    <a href="{% url 'reset' %}">Забыли пароль?</a>
    <p>Не зарегистрированы? <a href="{% url 'signup' %}"> Зарегистрироваться</a></p>
{% endblock %}

src/main/templates/main/main.html
{% extends 'main/main_base.html' %}
{% block title %}Главная{% endblock %}
{% load static %}
{% block base_content %}
    <div class="row">
        <img src="{% static 'media/main1.jpg' %}" class="max_cover_container col">
        <div class="col display-4 mt-5">оглянись</div>
    </div>
    <div class="row">
        <div class="col display-4 mt-5 ms-3">посмотри, какая красота тебя окружает</div>
        <img src="{% static 'media/main2.jpg' %}" class="max_cover_container float-end col">
    </div>
    <div class="row">
        <img src="{% static 'media/main3.jpg' %}" class="max_cover_container col">
        <div class="col display-4 mt-5">насладись ею</div>
    </div>
    <div class="row">
        <div class="col display-5 mt-5 ms-3">путешествуй, оно того стоит</div>
        <img src="{% static 'media/main4.jpg' %}" class="max_cover_container float-end col">
    </div>
    <div class="row">
        <div class="col mt-5 btn btn-default align-self-center border-dark">
            <a href="{% url 'trips' %}" class="p-5 display-6">Найти компанию для поездки</a></div>
    </div>
{% endblock %}

{% load static %}
{% block static_files %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock %}

src/main/templates/main/main_base.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    {% block static_files %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

</head>
<body class="d-flex h-100 bg-light">

<div class="d-flex w-110 h-100 mt-3 mx-auto flex-column">
    <header>
        <div class="container">
            <div class="nav nav-masthead row row-cols-6 justify-content-around">
                <div class="col-md-auto floa">
                    <a href="/"><h3 class="float-md-start mb-0 text-dark">Travel Together</h3></a>
                </div>
                <div class="col-md-auto">
                    <a class="nav-link" aria-current="page" href="{% url 'trips' %}">Поездки</a>
                </div>
                <div class="col-md-auto">
                    <a class="nav-link" href="{% url 'find' %}">Поиск</a>
                </div>
                <div class="col-md-auto">
                    <a class="nav-link" href="{% url 'blog:articles' %}">Статьи</a>
                </div>
                <div class="col-md-auto">
                    <a class="nav-link" href="{% url 'faq' %}">FAQ</a>
                </div>
                <div class="col-md-auto">
                    {% block navbar %}
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'account' user.id %}">Личный кабинет</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'login' %}">Личный кабинет</a>
                        {% endif %}
                        {% block header_account %} {% endblock %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </header>
    <div class="mx-auto mt-4">
        {% block base_content %}
        {% endblock %}
    </div>
</div>
<footer class="mt-auto text-white-50">
    <p>&copy; 2021 travel together</p>
</footer>
{% block scripts %}
{% endblock %}
</body>
</html>

src/main/templates/main/show_message.html
{% extends 'main/base.html' %}
{% block content %}
    <p>{{ message }}</p>
{% endblock %}

src/main/templates/main/test.html
    <h2 align="center">Прайс-лист</h2>
        <p>Какой-то текст или что угодно...</p>ут

src/main/templates/main/trips.html
{% extends 'main/base.html' %}
{% block title %}Поездки{% endblock %}
{% block content %}
    <div class="container mt-5">
        <h2>Поездки</h2>
        {% include 'main/partials/trip.html' with trips=trips %}
    </div>
{% endblock %}